image: python:3.5

pages:
  script:
  - pip install -r requirements.txt
  - pyvenv-3.5 env
  - source env/bin/activate
  - pip3 install Flask
  - python app-test.py
  artifacts:
    paths:
    - public
  only:
  - master